import turtle
turtle.speed(10)
def square():
    for i in range(3,80):
        turtle.forward(100)
        turtle.right(90)
        turtle.right(5)
turtle.pu()
turtle.backward(300)
turtle.right(90)
turtle.pd()
turtle.circle(300)
turtle.pu()
turtle.right(30)
turtle.goto(0,0)
turtle.pd()
square()
turtle.pu()
turtle.goto(30,60)
turtle.pd()
square()
turtle.right(60)
turtle.pu()
turtle.forward(300)
turtle.pd()
turtle.right(80)
turtle.fd(90)
turtle.right(60)
turtle.forward(5)

turtle.exitonclick()
